---
user: nobody
nginx_etc_path: /etc/nginx/proxy
nginx_log_path: /var/log/nginx/proxy
nginx_pid_path: /var/run/nginx-proxy.pid
nginx_lib_path: /var/lib/nginx/proxy
upstream_server: ey1-internal.groupsite.com
ssl_hosts:
  ### Groupsite owned
  - server_name: "www.groupsite.net"
    file_name:   _star_.groupsite.com
    ip_addr:     207.58.157.104
  - server_name: "groupsite.com *.groupsite.com"
    file_name:   _star_.groupsite.com
    ip_addr:     207.58.157.105
  - server_name: "groupsite.com *.groupsite.com"
    file_name:   _star_.groupsite.com
    ip_addr:     207.58.157.106
  - server_name: "collectivex.com *.collectivex.com"
    file_name:   _star_.collectivex.com
    ip_addr:     64.131.93.187

  ### Client owned (and mostly expired or unused!)
  - server_name: www.unitedundertakers.com
    file_name:   www.unitedundertakers.com
    ip_addr:     64.131.93.162
  - server_name: www.genderationy.net
    file_name:   www.genderationy.net
    ip_addr:     64.131.93.163
  - server_name: "*.empire20.ny.gov"
    file_name:   _star_.empire20.ny.gov
    ip_addr:     64.131.93.170
  - server_name: advocacynetwork.ctehealthcare.com
    file_name:   advocacynetwork.ctehealthcare.com
    ip_addr:     64.131.93.171
  - server_name: public-groups.nea.org
    file_name:   public-groups.nea.org
    ip_addr:     64.131.93.177
  - server_name: groups.nea.org
    file_name:   groups.nea.org
    ip_addr:     64.131.93.178
  - server_name: www.layerxperts.com
    file_name:   www.layerxperts.com
    ip_addr:     64.131.93.179
  - server_name: layerxperts.com
    file_name:   layerxperts.com
    ip_addr:     64.131.93.181
  - server_name: ciocouncil.ny.gov
    file_name:   ciocouncil.ny.gov
    ip_addr:     64.131.93.182
  - server_name: socialmediopolis.com
    file_name:   socialmediopolis.com
    ip_addr:     64.131.93.183
  - server_name: community.indialeadership.net
    file_name:   community.indialeadership.net
    ip_addr:     64.131.93.184
  - server_name: network.jobcorp.monster.com
    file_name:   network.jobcorp.monster.com
    ip_addr:     64.131.93.185
  - server_name: examinersandbox.examiner.com
    file_name:   examinersandbox.examiner.com
    ip_addr:     64.131.93.186
  - server_name: "*.groupsite.philau.edu"
    file_name:   _star_.groupsite.philau.edu
    ip_addr:     64.131.93.188
  - server_name: themurgesegroup.com
    file_name:   themurgesegroup.com
    ip_addr:     64.131.93.189
  - server_name: www.tylerpeople.com
    file_name:   www.tylerpeople.com
    ip_addr:     207.58.157.107
  - server_name: icopen.org
    file_name:   icopen.org
    ip_addr:     207.58.157.126

---
