---
user: nick
nginx_etc_path: /home/nick/src/work/nginx-servint-proxy
nginx_log_path: /home/nick/src/work/nginx-servint-proxy/tmp
nginx_pid_path: /home/nick/src/work/nginx-servint-proxy/tmp/nginx.pid
nginx_lib_path: /home/nick/src/work/nginx-servint-proxy/tmp
upstream_server: www.groupsite.com
ssl_hosts:
  - server_name: groups.nea.org
    file_name:   groups.nea.org
    ip_addr:     192.168.1.200
  - server_name: public-groups.nea.org
    file_name:   public-groups.nea.org
    ip_addr:     192.168.1.201
  - server_name: icopen.org
    file_name:   icopen.org
    ip_addr:     192.168.1.202
---
