---
user: www-data
nginx_etc_path: /etc/nginx
nginx_log_path: /var/log/nginx
nginx_pid_path: /var/run/nginx.pid
nginx_lib_path: /var/lib/nginx
upstream_server: www.groupsite.com
ssl_hosts:
  - server_name: public-groups.nea.org
    file_name:   public-groups.nea.org
---
